Repository AY2425S1-CS2103T-T10-3/tp, pull requests merged in 2024-10, with the labels that each got.

#60 Fix find logic
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: type.Bug, priority.High

#66 Amend PersonCard to display Tutorials
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Tutorial.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task, priority.High

#67 Improve student ID logic to ensure duplicates are not used
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#69 Customise GUI display
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.Medium

#70 Improve Email Logic to reject duplicate email addresses
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enhancement, priority.Low

#73 Update help
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.Low

#76 Update UG and README
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: type.Task, priority.Low

#72 Refactor Name class to improve name parsing
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enhancement, priority.High

#86 Allow for tutorials to be represented as not taken place
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/AttendanceStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Tutorial.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.css
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement, priority.Medium

#84 Fix mark/unmark error message
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
Labels: type.Bug, priority.Low, severity.VeryLow

#93 Add sort command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#85 Update mark/unmark commands to work on multiple students
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/CommandUtilTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Enhancement, priority.High

#97 Add commands to reset tutorials to not taken place
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ResetCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/parser/ResetCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium

#92 Add autofill previous input feature
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Enhancement, priority.Low

#101 Resolve access modifier bug
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, priority.High, severity.High

#106 Rename Jar file to ConTActs.jar
  build.gradle
Labels: type.Task, priority.Low, severity.Low

#107 Update model class diagram
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task, priority.Low

#109 Add autofill sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/AutoFillSequenceDiagram.puml
  docs/images/AutoFillSequenceDiagram.png
Labels: priority.Low, severity.Low

#110 Add SortCommand Activity Diagram
  docs/DeveloperGuide.md
  docs/diagrams/SortCommandActivityDiagram.puml
  docs/images/SortCommandActivityDiagram.png
Labels: type.Enhancement, priority.Low

#113 Allow finding by tag
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.Medium

#116 Update something
  docs/diagrams/BetterModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/CommandUtil.java
Labels: type.Task, priority.Low

#117 Update User Guide and Help Message
  docs/UserGuide.md
  docs/images/findAlexColleaguesResult.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement, priority.Medium
