Repository AY2425S1-CS2103T-T10-3/tp, pull requests merged in 2024-11, with the labels that each got.

#122 Improve parse index function
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ResetCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ResetCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Enhancement, type.Bug, priority.Medium, alpha-bug

#127 Update UG Command Summary table
  docs/UserGuide.md
Labels: severity.Low

#132 Sorting Command does unnecessary reordering
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/person/AttendanceStatus.java
  src/test/java/seedu/address/logic/commands/CommandUtilTest.java
  src/test/java/seedu/address/model/person/AttendanceStatusTest.java
Labels: alpha-bug

#123 Update DG
  docs/DeveloperGuide.md
  docs/images/BetterModelClassDiagram.png
Labels: type.Enhancement, priority.Low

#144 Update Sort Result Message
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: alpha-bug

#146 Update Sort Error Messages
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: alpha-bug

#145 Fix Tutorial Commands no feedback when empty display list
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/TutorialCommand.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
Labels: alpha-bug

#151 Update UG
  docs/UserGuide.md
Labels: alpha-bug

#159 Move Installation guide to top for new users
  docs/UserGuide.md
Labels: alpha-bug

#157 Update DG use cases
  docs/DeveloperGuide.md
Labels: alpha-bug

#161 Fix incorrect User Guide header
  docs/_sass/minima/_base.scss
  src/main/java/seedu/address/MainApp.java
Labels: alpha-bug

#160 Align all error messages to reduce inconsistency
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ResetCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/person/Tutorial.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ResetCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
Labels: alpha-bug

#233 Fix tutorial command silent errors and wrong error messages
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Tutorial.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, ped-code

#231 Ug update
  docs/UserGuide.md
  docs/images/MarkAfter.png
  docs/images/MarkBefore.png
  docs/images/Ui.png
  docs/images/findAlexColleaguesResult.png
  docs/images/findAlexDavidResult.png
  docs/images/findAlexTag.png
Labels: type.Enhancement, type.Bug

#236 Improve UG
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: ped-ug

#235 DG Edits
  docs/DeveloperGuide.md
  docs/diagrams/SortCommandActivityDiagram.puml
  docs/diagrams/SortCommandCheckPrefixRake.puml
  docs/images/SortCommandActivityDiagram.png
  docs/images/SortCommandCheckForPrefixesRake.png
Labels: ped-dg

#239 Fix UG bugs
  docs/UserGuide.md
Labels: ped-ug

#242 DG Fix and Duplicate Prefix fix
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.High, ped-dg, ped-code
